[package]
name = "postgrest"
version = "0.1.0"
authors = ["Bobbie Soedirgo <bobbie@soedirgo.dev>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
json = "0.12"
