name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Release on GitHub
        run: |
          npm i -g semantic-release
          npx semantic-release -p             \
            @semantic-release/commit-analyzer \
            @semantic-release/github          \
            @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
